name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - test_release-v*.*.*
    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_NAME: "${{ secrets.RELEASE_NAME }}-linux_amd64"
          UPLOAD_MODE: none
      - name: Build binaries
        run: /bin/bash -c "source $GITHUB_WORKSPACE/github-actions/build-linux.sh"
        env:
          RELEASE_NAME: ${{ secrets.RELEASE_NAME }}-linux_amd64.zip
      - shell: bash
        run: |
          ls
      - name: Publish release
        run: /bin/bash -c "source $GITHUB_WORKSPACE/github-actions/release-linux.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          RELEASE_NAME: ${{ secrets.RELEASE_NAME }}

