name: Rust

on:
  push:
    branches: [ "mainan" ]
  pull_request:
    branches: [ "mainan" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none

      - shell: bash
        run: |
           pwd
           ls
