name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
    
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Bump version and push tag/create release point
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        WITH_V: true
      id: bump_version
          
  linux:
      needs: release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Compile
          id: compile
          uses: rust-build/rust-build.action@v1.4.0
          with:
            RUSTTARGET: x86_64-unknown-linux-musl
            ARCHIVE_NAME: "${{ secrets.RELEASE_NAME }}-linux_amd64"
            UPLOAD_MODE: none
        - name: Build binaries
          run: /bin/bash -c "source $GITHUB_WORKSPACE/github-actions/build-linux.sh"
          env:
            RELEASE_NAME: ${{ secrets.RELEASE_NAME }}-linux_amd64.zip
        - name: Upload binary to release
          uses: svenstaro/upload-release-action@2.3.0
          with:
            repo_token: ${{ secrets.GIT_TOKEN }}
            file: ${{ github.workspace }}/${{ secrets.RELEASE_NAME }}-linux_amd64.zip
            asset_name: ${{ secrets.RELEASE_NAME }}-linux_amd64.zip
            tag: ${{ steps.bump_version.outputs.new_tag }}
            overwrite: true

